export enum Direction {
  BACKEND = 'BACKEND',
  FRONTEND = 'FRONTEND',
  DEVOPS = 'DEVOPS',
  GAME_DEV = 'GAME_DEV',
  MOBILE = 'MOBILE',
  DESKTOP = 'DESKTOP',
  EMBEDDED = 'EMBEDDED',
  DATA_SCIENTIST = 'DATA SCIENTIST',
  DATA_ANALYST = 'DATA ANALYST',
  DATA_ENGINEER = 'DATA_ENGINEER',
  QA = 'QA',
  CUSTOMER = 'CUSTOMER'
}